events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile        on;
    keepalive_timeout  65;

    server {
        listen 80;
        server_name localhost 192.168.1.68;

        root C:/nginx-1.28.0/html;

        # FastAPI proxy
        location /api/ {
            proxy_pass http://127.0.0.1:8080/api/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_connect_timeout 1800s;
            proxy_send_timeout 1800s;
            proxy_read_timeout 1800s;
            proxy_buffer_size 128k;  # Increase for large responses
            proxy_buffers 8 128k;    # Buffer settings to handle large data
        }

        # phpMyAdmin location
        location ~ ^/phpmyadmin(/.*)?$ {
            alias C:/xampp/phpmyadmin$1;
            index index.php;

            if ($request_uri ~ ^/phmyadmin(/?)$) {
                rewrite ^ /phpmyadmin/ permanent;
            }

            location ~ ^/phpmyadmin/(.+\.php)$ {
                alias C:/xampp/phpmyadmin/$1;
                fastcgi_pass 127.0.0.1:9000;
                fastcgi_index index.php;
                fastcgi_param SCRIPT_FILENAME $request_filename;
                include fastcgi_params;
            }
        }

        location ~ /\. {
            deny all;
        }

        error_page 404 /404.html;
        location = /404.html {
            root html;
        }
    }
}